/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Fri Jun 28 13:58:58 2019. */

#include "service.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t echo_request_fields[2] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, echo_request, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t echo_response_fields[2] = {
    PB_FIELD(  1, BYTES   , REQUIRED, STATIC  , FIRST, echo_response, data, data, 0),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
#error Field descriptor for echo_response.data is too large. Define PB_FIELD_32BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
